import styles from './MainLayout.module.css';
import Head from 'next/head';
import { Navbar } from '../Navbar';

import { Geist, Geist_Mono } from "next/font/google";
import { FC, PropsWithChildren } from 'react';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const MainLayout: FC<PropsWithChildren> = ({children}) => {
  // console.log('---->', children);
    return (
    <>
      <Head>
        <title>Create Next Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        className={`${styles.page} ${geistSans.variable} ${geistMono.variable}`}
      >
        <Navbar></Navbar>
        <main className={styles.main}>
          {children}
        </main>
      </div>
    </>
  );
}